# Generated by Django 6.0 on 2026-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user account is active. Defaults to False and user needs to verify email on signup before it can be set to True.'),
        ),
    ]
