# Generated by Django 6.0 on 2026-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_post_paragraph_count_post_read_time_post_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
